Repository dsu-arl/pace-cybher-dojo, pull requests merged in 2025-05, with the labels that each got.

#8 [Cryptography] New Module
  cryptography/DESCRIPTION.md
  cryptography/module.yml
  dojo.yml
Labels: new module

#9 [Cryptography] Adding Existing Caesar Cipher Challenges
  cryptography/caesar-cipher-brute-force/DESCRIPTION.md
  cryptography/caesar-cipher-brute-force/_0/.config
  cryptography/caesar-cipher-brute-force/_1/.config
  cryptography/caesar-cipher-brute-force/_2/.config
  cryptography/caesar-cipher-brute-force/_3/.config
  cryptography/caesar-cipher-brute-force/_4/.config
  cryptography/caesar-cipher-brute-force/_5/.config
  cryptography/caesar-cipher-brute-force/_6/.config
  cryptography/caesar-cipher-brute-force/_7/.config
  cryptography/caesar-cipher-brute-force/_8/.config
  cryptography/caesar-cipher-brute-force/_9/.config
  cryptography/caesar-cipher-brute-force/verify
  cryptography/caesar-cipher-decryption/DESCRIPTION.md
  cryptography/caesar-cipher-decryption/verify
  cryptography/caesar-cipher-encryption/DESCRIPTION.md
  cryptography/caesar-cipher-encryption/verify
  cryptography/caesar-cipher-scripting/DESCRIPTION.md
  cryptography/caesar-cipher-scripting/_0/.config
  cryptography/caesar-cipher-scripting/_1/.config
  cryptography/caesar-cipher-scripting/_2/.config
  cryptography/caesar-cipher-scripting/_3/.config
  cryptography/caesar-cipher-scripting/_4/.config
  cryptography/caesar-cipher-scripting/_5/.config
  cryptography/caesar-cipher-scripting/_6/.config
  cryptography/caesar-cipher-scripting/_7/.config
  cryptography/caesar-cipher-scripting/_8/.config
  cryptography/caesar-cipher-scripting/_9/.config
  cryptography/caesar-cipher-scripting/verify
  cryptography/module.yml
Labels: new challenge

#11 [Cryptography] Adding Existing ASCII Challenges
  cryptography/ascii-decoding/DESCRIPTION.md
  cryptography/ascii-decoding/verify
  cryptography/ascii-encoding/DESCRIPTION.md
  cryptography/ascii-encoding/verify
  cryptography/module.yml
Labels: new challenge

#17 [Cryptography] Morse Code Encoding
  cryptography/module.yml
  cryptography/morse-code-encoding/DESCRIPTION.md
  cryptography/morse-code-encoding/verify
Labels: new challenge

#22 [Cryptography] Morse Code Decoding
  cryptography/module.yml
  cryptography/morse-code-decoding/DESCRIPTION.md
  cryptography/morse-code-decoding/verify
Labels: new challenge

#20 Feature/forensics
  dojo.yml
  forensics/DESCRIPTION.md
  forensics/chatty-server/DESCRIPTION.md
  forensics/chatty-server/verify
  forensics/code-cracker/DESCRIPTION.md
  forensics/code-cracker/verify
  forensics/google-dorks/DESCRIPTION.md
  forensics/google-dorks/verify
  forensics/grep-master/DESCRIPTION.md
  forensics/grep-master/verify
  forensics/hidden-treasures-in-the-picture/DESCRIPTION.md
  forensics/hidden-treasures-in-the-picture/verify
  forensics/locked-treasure-chest/DESCRIPTION.md
  forensics/locked-treasure-chest/verify
  forensics/module.yml
  forensics/secret-message-in-photo/DESCRIPTION.md
  forensics/secret-message-in-photo/verify
  forensics/socialmediapassword/.init
  forensics/socialmediapassword/DESCRIPTION.md
  forensics/socialmediapassword/run
  forensics/socialmediapassword/static/books.jpg
  forensics/socialmediapassword/static/cake.jpg
  forensics/socialmediapassword/static/dog.jpg
  forensics/socialmediapassword/static/style.css
  forensics/socialmediapassword/templates/index.html
  forensics/socialmediapassword/verify
  forensics/the-artists-clue/DESCRIPTION.md
  forensics/the-artists-clue/verify
  forensics/unlock-the-vault/DESCRIPTION.md
  forensics/unlock-the-vault/verify
  forensics/waybackmachinei/DESCRIPTION.md
  forensics/waybackmachinei/run
  forensics/waybackmachinei/verify
  forensics/waybackmachinei/wayback_dsu_results.png
  forensics/waybackmachinei/wayback_dsu_snapshot_select.png
  forensics/waybackmachinei/wayback_dsu_webpage_result.png
  forensics/waybackmachinei/wayback_search.png
  forensics/waybackmachinei/wayback_why_dsu.png
  forensics/waybackmachineii/DESCRIPTION.md
  forensics/waybackmachineii/run
  forensics/waybackmachineii/verify
Labels: new challenge

#18 Feature/linux module updates
  linux/DESCRIPTION.md
  linux/advanceddirectories/solve
  linux/cattingfiles/DESCRIPTION.md
  linux/cattingfiles/solve
  linux/commandflags/solve
  linux/directories/DESCRIPTION.md
  linux/directories/solve
  linux/filecreation/DESCRIPTION.md
  linux/filecreation/solve
  linux/findingcontent/DESCRIPTION.md
  linux/findingcontent/solve
  linux/findingfiles/solve
  linux/module.yml
  linux/movingfiles/DESCRIPTION.md
  linux/movingfiles/solve
  linux/nanocreatefile/DESCRIPTION.md
  linux/nanocreatefile/solve
  linux/nanoeditfile/DESCRIPTION.md
  linux/nanoeditfile/solve
  linux/running-commands/DESCRIPTION.md
  linux/running-commands/run_this_file
Labels: new challenge, edit challenge
