Repository dsu-arl/pace-cybher-dojo, pull requests merged in 2025-06, with the labels that each got.

#42 [Forensics] Grep Master
  forensics/Dockerfile
  forensics/grep-master/DESCRIPTION.md
  forensics/grep-master/haystack.txt
  forensics/grep-master/verify
  forensics/module.yml
  forensics/unlock-the-vault/vault_clue.txt
Labels: new challenge

#51 feature/base64-encoding
  cryptography/base64-encoding/DESCRIPTION.md
  cryptography/base64-encoding/verify
  cryptography/module.yml
Labels: new challenge

#58 [Cryptography] Hard Challenge #1
  cryptography/hard-challenge-1/DESCRIPTION.md
  cryptography/hard-challenge-1/verify
  cryptography/module.yml
Labels: new challenge

#59 Feature/swiss army button
  web/module.yml
  web/pale-red-horse-squad/verify
  web/swiss-army-button/DESCRIPTION.md
  web/swiss-army-button/static/app.js
  web/swiss-army-button/static/calc.png
  web/swiss-army-button/static/chess.jpg
  web/swiss-army-button/static/frog.avif
  web/swiss-army-button/templates/advice.html
  web/swiss-army-button/templates/archive.html
  web/swiss-army-button/templates/calculator.html
  web/swiss-army-button/templates/chess.html
  web/swiss-army-button/templates/flag.html
  web/swiss-army-button/templates/frog.html
  web/swiss-army-button/templates/index.html
  web/swiss-army-button/templates/lorem.html
  web/swiss-army-button/verify
Labels: new challenge

#56 Feature/python math
  python/DESCRIPTION.md
  python/comparison/DESCRIPTION.md
  python/comparison/pacePythonTester
  python/comparison/verify
  python/easy-math/DESCRIPTION.md
  python/easy-math/pacePythonTester
  python/easy-math/verify
  python/floor-division/DESCRIPTION.md
  python/floor-division/pacePythonTester
  python/floor-division/verify
  python/geometry/DESCRIPTION.md
  python/geometry/pacePythonTester
  python/geometry/verify
  python/math/DESCRIPTION.md
  python/math/pacePythonTester
  python/math/verify
  python/module.yml
Labels: new challenge, edit challenge

#69 feature/playfair-encoding
  cryptography/module.yml
  cryptography/playfair-encoding/DESCRIPTION.md
  cryptography/playfair-encoding/verify
Labels: new challenge

#63 [Cryptography] Polybius Square Decoding
  cryptography/module.yml
  cryptography/polybius-square-decoding/DESCRIPTION.md
  cryptography/polybius-square-decoding/verify
Labels: new challenge

#65 [Cryptography] Rail Fence Encoding
  cryptography/module.yml
  cryptography/rail-fence-encoding/DESCRIPTION.md
  cryptography/rail-fence-encoding/verify
Labels: new challenge

#79 [Forensics] code cracker
  forensics/.init
  forensics/Dockerfile
  forensics/chatty-server/DESCRIPTION.md
  forensics/chatty-server/server.log
  forensics/chatty-server/verify
  forensics/code-cracker/DESCRIPTION.md
  forensics/code-cracker/secret.bin
  forensics/code-cracker/verify
Labels: new challenge

#78 [Forensics] chatty server
  forensics/Dockerfile
Labels: new challenge

#80 [Forensics] the artists clue
  forensics/.init
  forensics/Dockerfile
  forensics/the-artists-clue/DESCRIPTION.md
  forensics/the-artists-clue/art.jpg
  forensics/the-artists-clue/verify
Labels: new challenge

#83 Feature/python add functions challenges
  python/DESCRIPTION.md
  python/function-arguments/DESCRIPTION.md
  python/function-arguments/pacePythonTester
  python/function-arguments/verify
  python/module.yml
  python/return-values/DESCRIPTION.md
  python/return-values/pacePythonTester
  python/return-values/verify
  python/temp.yml
  python/user-defined/DESCRIPTION.md
  python/user-defined/pacePythonTester
  python/user-defined/verify
Labels: new challenge

#88 New Challenge -- [Web] Am I Admin?
  web/am-i-admin/DESCRIPTION.md
  web/am-i-admin/app.py
  web/am-i-admin/templates/admin.html
  web/am-i-admin/templates/home.html
  web/am-i-admin/templates/login.html
  web/module.yml
Labels: new challenge

#97 Change bad bad to good good
  linux/directories/solve
Labels: edit challenge
